apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"clickhouse","namespace":"default"},"spec":{"ports":[{"name":"http","port":8123,"targetPort":8123},{"name":"native","port":9000,"targetPort":9000}],"selector":{"app":"clickhouse"}}}
  creationTimestamp: "2026-05-31T08:04:54Z"
  name: clickhouse
  namespace: default
  resourceVersion: "37068"
  uid: 7f9f32ef-fa6b-4a43-a922-6dee401e23f7
spec:
  clusterIP: 10.96.83.228
  clusterIPs:
  - 10.96.83.228
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: native
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: clickhouse
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
